# Python: More Data Annotation and Numpy

Name:
Liping He
abc123:
llt949
Blank notebook to be used for class exercises.

## Exercise 1

Given the provided numpy array, write code that prints the following:
    
- Print the third row of the array
- Print the second column of the array
- Print the fourth row's third column (this should print a single number).

In [2]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

In [3]:
# Write Code Here
m0_sum = 0
m1_sum = 0
f_sum = 0
for g in grades[:3]:
    print(g[:2])
for g in grades:
    m0_sum += g[0]
    m1_sum += g[1]
    f_sum += g[2]
    
ns = len(grades)
print(m0_sum/ns, m1_sum/ns, f_sum/ns)

[79 95]
[95 60]
[99 67]
84.1 74.5 80.1


In [8]:
print(grades[0])

[79 95 60]


## Exercise 2

Given the provided array in the Lab file, write code the prints the following:

- The average grade per test (column) (this should print an array with 3 items)
- The average grade per row, i.e., the average test grade per student
- Print the max grade per test
- Print the average across all students (rows) and tests (columns)

In [8]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array
print(grades[:3,:2])

[[79 95]
 [95 60]
 [99 67]]


In [9]:
# Write Code Here
# Write Code Here
print(grades.mean(axis=0)) #per col
print(grades.mean(axis=1)) #per row
print(grades.max(axis=0))
print(grades.mean())

[84.1 74.5 80.1]
[78.         72.         83.33333333 83.         91.         78.33333333
 76.33333333 73.33333333 77.33333333 83.        ]
[99 95 98]
79.56666666666666


## Exercise 3

Write code that prints the grades of all students that have an average grade less than 90.

In [10]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

In [11]:
avg = grades.mean(axis=1)
print(avg)
bool_index = avg <90
print(bool_index)
print(grades[bool_index, :])

[78.         72.         83.33333333 83.         91.         78.33333333
 76.33333333 73.33333333 77.33333333 83.        ]
[ True  True  True  True False  True  True  True  True  True]
[[79 95 60]
 [95 60 61]
 [99 67 84]
 [76 76 97]
 [70 69 96]
 [88 65 76]
 [67 73 80]
 [82 89 61]
 [94 67 88]]


## Exercise 4

Write code to adds 10 points every student's test grade **if** their average test grade is greater than 90.

In [5]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

In [13]:
# Write Code Here
new_grades = grades.copy()
index_bool = grades.mean(axis=1) >90
print(index_bool)

new_grades[index_bool]+=10
new_grades

[False False False False  True False False False False False]


array([[ 79,  95,  60],
       [ 95,  60,  61],
       [ 99,  67,  84],
       [ 76,  76,  97],
       [101,  94, 108],
       [ 70,  69,  96],
       [ 88,  65,  76],
       [ 67,  73,  80],
       [ 82,  89,  61],
       [ 94,  67,  88]])

## Exercise 5

Write a function that takes two 1-dimensional arrays as input and returns the euclidean distance between the two arrays.

Euclidean distance is defined as

$EDist = \sqrt{(x_0 - v_0)^2 + (x_1 - v_1)^2 + \dots + (x_{D-1} - v_{D-1})^2}$

The square root of a number in numpy can be calculated as np.sqrt(x), where x is a number or array.

Try to complete this exercise with for loops and with vector notation.

In [45]:
# Write Code Here
def edist1(x,y):
    score = 0
    for i, j in zip(x,y):
        score +=(i-j)**2
    return score**0.5

def edist2(x,y):
    return np.sqrt(((x-y)**2).sum())
    
    
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])  
             
print(edist1(x,y), edist2(x,y))

8.0 8.0


## Exercise 6

Write code to load the data in the "iris.csv" into numpy arrays.

The frst 4 columns are the features/attributes. The last column is the
class. Simply load the class as a list of strings. Don't forget to convert the
dataset into a numpy array. You can use either DictVectorizer or the CSV
method on the previous slide to load the features.

In [1]:
with open('./iris.csv') as in_file:
    count = 0
    for row in in_file:
        print(row.strip())
        count += 1
        if count == 10:
            break

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5.0,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa


In [3]:
# Write code here
import numpy as np
import csv

x =[]
y = []
my_file = open('iris.csv')
iCSV = csv.reader(my_file, delimiter =',')
for row in iCSV:
    x.append([float(x) for x in row[:-1]])
    y.append(row[-1])
my_file.close
x= np.array(x)
y= np.array(y)
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [5]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [17]:
from sklearn.feature_extraction import DictVectorizer
x_list_dic =[]
y = []
my_file = open('./iris.csv')
iCSV = csv.reader(my_file, delimiter =',')
for row in iCSV:
    features = {'col_1':float(row[0]),
                'col_2':float(row[1]),
                'col_3':float(row[2]),
                'col_4':float(row[3])}
    x_list_dic.append(features)
    y.append(row[-1])
my_file.close
vec = DictVectorizer(sparse = False)

x = vec.fit_transform(x_list_dic)
y= np.array(y)
print(x.shape)
print(y.shape)
vec.feature_names_

NameError: name 'csv' is not defined

In [2]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])

In [3]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
print(b.mean(axis=0))

[2.5 3.5 4.5]


In [6]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

In [11]:
grades[grades[:,2]<70]

array([[79, 95, 60],
       [95, 60, 61],
       [82, 89, 61]])

In [12]:
scaling = [1.1, 1.05, 1.03]

In [14]:
np.diag(scaling)

array([[1.1 , 0.  , 0.  ],
       [0.  , 1.05, 0.  ],
       [0.  , 0.  , 1.03]])

In [15]:
grades.dot(np.diag(scaling))

array([[ 86.9 ,  99.75,  61.8 ],
       [104.5 ,  63.  ,  62.83],
       [108.9 ,  70.35,  86.52],
       [ 83.6 ,  79.8 ,  99.91],
       [100.1 ,  88.2 , 100.94],
       [ 77.  ,  72.45,  98.88],
       [ 96.8 ,  68.25,  78.28],
       [ 73.7 ,  76.65,  82.4 ],
       [ 90.2 ,  93.45,  62.83],
       [103.4 ,  70.35,  90.64]])

In [16]:
grades.max(axis=0)
maxInExam = grades.max(axis=0)
grades.dot(np.diag(100/maxInExam)).round()

array([[ 80., 100.,  61.],
       [ 96.,  63.,  62.],
       [100.,  71.,  86.],
       [ 77.,  80.,  99.],
       [ 92.,  88., 100.],
       [ 71.,  73.,  98.],
       [ 89.,  68.,  78.],
       [ 68.,  77.,  82.],
       [ 83.,  94.,  62.],
       [ 95.,  71.,  90.]])

In [29]:
grades.sort()


In [30]:
grades

array([[60, 79, 95],
       [60, 61, 95],
       [67, 84, 99],
       [76, 76, 97],
       [84, 91, 98],
       [69, 70, 96],
       [65, 76, 88],
       [67, 73, 80],
       [61, 82, 89],
       [67, 88, 94]])

In [33]:
a = [1, 1, 1]
b = [1, 1, 1]
a = np.array(a)
b = np.array(b)

In [35]:
a-b

array([0, 0, 0])

In [36]:
np.size(a)

3

In [38]:

a = np.array([[1, 1],[2, 1]])
b = np.array([[1, 1],[2, 1]])

In [40]:
np.size(grades)

30

In [42]:
a = [[79, 95],
          [95, 60],
          [99, 67],
          [76, 76],
          [91, 84],
          [70, 69],
          [88, 65],
          [67, 73],
          [82, 89],
          [94, 67]]

In [48]:
b= [[79, 95],
          [95, 60],
          [99, 67],
          [76, 76],[91, 84]]

In [49]:
a= np.array(a)
b = np.array(b)

In [47]:
a.dot(b)

ValueError: shapes (10,2) and (5,2) not aligned: 2 (dim 1) != 5 (dim 0)