# Machine Learning and NLP

Name:

abc123:

Blank notebook to be used for class exercises.

## Exercise 1

Write code to load the data in the "iris.csv" into numpy arrays.

The frst 4 columns are the features/attributes. The last column is the
class. Simply load the class as a list of strings. Don't forget to convert the
dataset into a numpy array. You can use either DictVectorizer or the CSV
method on the previous slide to load the features.

In [1]:
with open('iris.csv') as in_file:
    count = 0
    for row in in_file:
        print(row.strip())
        count += 1
        if count == 10:
            break

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5.0,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa


In [5]:
import numpy as np
import csv
from sklearn.feature_extraction import DictVectorizer
# Write code here
#model 
X = []
y =[]
with open('iris.csv') as in_file:
    iCSV = csv.reader(in_file, delimiter =',')
    for row in iCSV:
        tmp = []
        for f in row[:-1]:
            tmp.append(float(f)) #tmp = [float(f) for f in row[:-1]]
        X.append(tmp)
        y.append(row[-1])
X = np.array(X)
y = np.array(y)

In [6]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [21]:
vec = DictVectorizer(sparse = False)
X_dicts = []
y =[]
with open ('iris.csv') as in_file:
    iCSV = csv.reader(in_file, delimiter =',')
    for row in iCSV:
        tmp = {"f0":float(row[0]),
               "f1":float(row[1]),
               "f2":float(row[2]),
               "f3":float(row[3])}
        X_dicts.append(tmp)
        y.append(row[-1])
X = vec.fit_transform(X_dicts)
y= np.array(y)

In [22]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

## Exercise 2

Using the iris data you loaded in Exercise 1, do the following:

- Use train_test_split() to divide the iris dataset. (use 0.2 for the
test size). Set random_state to 42.
- Train an SVM on the train split and evaluate using accuracy on the
test split.
- Fiddle with the parameters of the SVM to see how it effects the
performance.
- Calculate the accuracy on the train split. Is there a difference between the train/test accuracies?

Next, try using a different classifier, a random forest, and see how it
compares to the SVM

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

Note that this is a toy dataset, so all scores will be high.

In [23]:
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split, GridSearchCV

import numpy as np
np.random.seed(32)
import random
random.seed(32)

# Write code here
X_train, X_val, y_train, y_val = train_test_split(X,y,test_size = 0.5)

In [24]:
print(X_train.shape, X_val.shape)

(75, 4) (75, 4)


In [29]:
clf = SVC()
clf.fit(X_train, y_train)
preds = clf.predict(X_val)
print(accuracy_score(y_val, preds))

0.9333333333333333


In [26]:
preds = clf.predict(X_train)
print(accuracy_score(y_train, preds))

0.96


In [27]:
clf = SVC(C=.0000001)
clf.fit(X_train, y_train)
preds = clf.predict(X_val)
print(accuracy_score(y_val, preds))

0.28


In [28]:
preds = clf.predict(X_train)
print(accuracy_score(y_train, preds))

0.38666666666666666


## Exercise 3

Using the train/test iris dataset split from exercise 2. Train a model on the training dataset using GridSearchCV with the SVC kernel parameters "rbf" and "linear",and C parameters 0.001, 0.01, 0.1, 1., and 10. Print the training and
validation scores for the best set of parameters.


In [30]:
X_train, X_text, y_train, y_test = train_test_split(X,y,test_size =0.5)

In [10]:
svc = SVC()
params ={'kernel':['rbf','linear'], 'C':[0.001,0.01,0.1,1.,10.]}
clf =GridSearchCV(svc, params, cv =3)
clf.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid={'C': [0.001, 0.01, 0.1, 1.0, 10.0],
                         'kernel': ['rbf', 'linear']})

In [32]:
clf.best_params_

{'C': 1.0, 'kernel': 'linear'}

In [33]:
clf.best_score_

0.9866666666666667

In [34]:
preds = clf.predict(X_train)
print(accuracy_score(y_train, preds))

0.9866666666666667


## Exercise 4

The tab (\t) separated file "sentiment-twitter-data.tsv" contains tweets annotated for sentiment. Load the data then do the following:

- split the dataset into a train/test split.
- create a bag of words feature representation for the tweets using the CountVectorizer
- Use grid-search (CV) on the train split to find the best C parameters for a LinearSVC classifier. Only test 2 C values to reduce overhead (0.1 and 1.). Also, use a 2-fold CV, i.e., cv=2.
- report (print) the accuracy, micro F1, and macro F1 of the final classifier on the test data and train data
- How many features were created with the bag of words representation?

file path: ./sentiment-twitter-data.tsv

In [16]:
# This is a tab seperated file, so with csv reader use delimiter="\t"
with open('./sentiment-twitter-data.tsv') as in_file:
    count = 0
    for row in in_file:
        print(row.strip())
        count += 1
        if count == 10:
            break

264183816548130816	15140428	positive	Gas by my house hit $3.39!!!! I'm going to Chapel Hill on Sat. :)
264249301910310912	18516728	negative	Iranian general says Israel's Iron Dome can't deal with their missiles (keep talking like that and we may end up finding out)
264105751826538497	147088367	positive	with J Davlar 11th. Main rivals are team Poland. Hopefully we an make it a successful end to a tough week of training tomorrow.
264094586689953794	332474633	negative	Talking about ACT's &amp;&amp; SAT's, deciding where I want to go to college, applying to colleges and everything about college stresses me out.
254941790757601280	557103111	negative	They may have a SuperBowl in Dallas, but Dallas ain't winning a SuperBowl. Not with that quarterback and owner. @S4NYC @RasmussenPoll
264169034155696130	382403760	neutral	Im bringing the monster load of candy tomorrow, I just hope it doesn't get all squiched
263192091700654080	344222239	objective-OR-neutral	Apple software, retail chiefs out in o

In [35]:
import csv

import numpy as np
np.random.seed(42)
import random
random.seed(42)

#Write code here
from sklearn.feature_extraction.text import CountVectorizer
X_txt = []
y = []
with open('./sentiment-twitter-data.tsv') as in_file:
    iCSV = csv.reader(in_file, delimiter = '\t')
    for row in iCSV:
        X_txt.append(row[-1])
        y.append(row[2])
print(len(X_txt), len(y))
X_txt = np.array(X_txt)
y = np.array(y)

8002 8002


In [36]:
print(y)

['positive' 'negative' 'positive' ... 'neutral' 'positive' 'negative']


In [34]:
import numpy as np
np.random.seed(32)
import random
random.seed(32)

X_txt_train, X_txt_text, y_train, y_test=train_test_split(X_txt,y,test_size=0.2)

In [37]:
vec = CountVectorizer(ngram_range=(1,1), min_df=3)
X_train = vec.fit_transform(X_txt_train)
X_test = vec.transform(X_txt_text)
print(X_train.shape, X_test.shape)
print(X_train)

(6401, 4302) (1601, 4302)
  (0, 2331)	1
  (0, 2724)	1
  (0, 3689)	1
  (0, 767)	1
  (0, 1382)	1
  (0, 1970)	1
  (0, 3518)	1
  (0, 1112)	1
  (0, 3859)	2
  (0, 2193)	1
  (0, 337)	1
  (0, 1520)	1
  (0, 433)	1
  (0, 3787)	1
  (0, 1765)	1
  (0, 1750)	1
  (0, 2700)	1
  (0, 1628)	1
  (0, 3995)	1
  (0, 2500)	1
  (0, 1871)	1
  (0, 2396)	1
  (1, 2724)	1
  (1, 1970)	1
  (1, 3859)	1
  :	:
  (6399, 2053)	1
  (6399, 595)	1
  (6399, 3953)	1
  (6399, 1315)	1
  (6399, 319)	1
  (6399, 2562)	1
  (6399, 3268)	1
  (6399, 4143)	1
  (6400, 3859)	1
  (6400, 1871)	1
  (6400, 3789)	1
  (6400, 4190)	1
  (6400, 363)	1
  (6400, 876)	1
  (6400, 1559)	1
  (6400, 267)	1
  (6400, 3810)	1
  (6400, 2607)	1
  (6400, 3793)	1
  (6400, 523)	1
  (6400, 1029)	1
  (6400, 2041)	1
  (6400, 163)	1
  (6400, 3606)	1
  (6400, 3183)	1


In [38]:
vec.get_feature_names()[500:510]

['bharatiya',
 'bias',
 'bid',
 'biden',
 'bieber',
 'biebers',
 'big',
 'bigger',
 'biggest',
 'bike']

In [39]:
vec.vocabulary_['bharatiya']

500

In [18]:
vec.get_feature_names()[500]

'bharatiya'

In [40]:
svc = LinearSVC()
params = {"C":[0.001,0.01,0.1,1.,10.]}
clf =GridSearchCV(svc, params,cv=3)
clf.fit(X_train, y_train)


/Users/lilyhe/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/lilyhe/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/Users/lilyhe/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


GridSearchCV(cv=3, estimator=LinearSVC(),
             param_grid={'C': [0.001, 0.01, 0.1, 1.0, 10.0]})

In [41]:
clf.best_params_

{'C': 0.01}

In [43]:
clf.best_score_

0.44977337280177765

In [44]:
preds = clf.predict(X_test)
print(accuracy_score(y_test, preds))

0.44597126795752656


In [23]:
preds = clf.predict(X_train)
print(accuracy_score(y_train, preds))

0.6914544602405874


In [2]:
import numpy as np
vec = np.zeros((3,))
classes = ["blue","red","green"]
vec[classes.index("green")] =1
vec

array([0., 0., 1.])

In [6]:
from sklearn.feature_extraction import DictVectorizer
datasetDicts =[{'age':1, 'hair_color':'blue'},{'age':2,'hair_color':'green'}]
vec =DictVectorizer(sparse=False)
dataset = vec.fit_transform(datasetDicts)
dataset

array([[1., 1., 0.],
       [2., 0., 1.]])

In [8]:
new_data =[{'age':3, 'hair_color':'purple'}]
nex_X = vec.transform(new_data)

In [9]:
nex_X

array([[3., 0., 0.]])

In [10]:
dara= [{'age':3, 'hair_color':'purple','is_smoker':0}]

In [13]:
dara

[{'age': 3, 'hair_color': 'purple', 'is_smoker': 0}]

In [16]:
from sklearn.feature_extraction import DictVectorizer
datasetDicts1 =[{'age':1, 'hair_color':'blue'},{'age':2,'hair_color':'green'}]
vec1 =DictVectorizer(sparse=False)
dataset1 = vec.transform(datasetDicts1)
dataset1

array([[1., 1., 0.],
       [2., 0., 1.]])

In [48]:
atts1= [[0.,1.,1.],[1.,0.,0.]]
atts2= [[1.,1.,0.],[2.,0.,1.]]
combie_atts = np.hstack([atts1,atts2])

In [50]:
atts1= [[0.,1.,1],[1.,0.,0.]]
atts2= [[1.,1.,0.],[2.,0.,1.]]
combie_atts = np.hstack([atts1,atts2])

In [21]:
combie_atts

array([[0., 1., 1., 1., 1., 0.],
       [1., 0., 0., 2., 0., 1.]])

In [ ]:
myData.csv
label, feature 1, feature 2
positive, 0.1,1
positive, 1,7
positive, 3,4

In [ ]:
import numpy as np
import csv
from sklearn.feature_extraction import DictVectorizer
# Write code here
#model 
X = []
y =[]
with open('myData.csv') as in_file:
    iCSV = csv.reader(in_file, delimiter =',')
    next(iCSV)
    for row in iCSV: #tmp = [float(f) for f in row[:-1]]
        X.append([float(x) for x in row[1:]])
        y.append(row[0])
X = np.array(X)
y = np.array(y)

In [23]:
from sklearn import datasets
raw_data = datasets.load_wine()
X= raw_data["data"]
y= raw_data["target"]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [27]:
from sklearn.model_selection import train_test_split, GridSearchCV
X_train, X_val, y_train, y_val = train_test_split(X,y,test_size = 0.2)
from sklearn.svm import SVC
clf = SVC()
clf.fit(X_train, y_train)

SVC()